name: CI/CD Pipeline

on:
  push:
    branches:
      - dev  # Run tests on every push to the dev branch
  pull_request:
    branches:
      - main  # Run tests for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install --prefix client
          npm install --prefix server

      # Run client tests
      - name: Run client tests
        run: |
          npm test --prefix client

      # Run server tests
      - name: Run server tests
        run: |
          npm test --prefix server

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test  # Ensure the test job passes before running
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Build and Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --prod \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --project-id ${{ secrets.VERCEL_PROJECT_ID }} \
            --org-id ${{ secrets.VERCEL_ORG_ID }}
