name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install --prefix client
          npm install --prefix server

      - name: Run client tests
        run: |
          npm test --prefix client

      - name: Run server tests
        run: |
          chmod +x server/node_modules/.bin/jest
          npm test --prefix server

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --prod \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --project-id ${{ secrets.VERCEL_PROJECT_ID }} \
            --org-id ${{ secrets.VERCEL_ORG_ID }}
